/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package konterhp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Cari extends javax.swing.JFrame {

    static String identifier, pilihan;
    ArrayList<String> ket = new ArrayList<>();
    private DefaultTableModel model;
    Kasir halamanKasir;
    Connection conn;
    PreparedStatement ps;
    Statement cs;
    ResultSet rs;
    public boolean isBarcode = false;

    /**
     * Creates new form Cari
     */
    public Cari() {
        initComponents();
        model = new DefaultTableModel();
        //digunakan untuk memberi heading / judul pada kolom di tabel buku
        tbPencarian.setModel(model);
// "table_buku sesuaikan dengan variabel name"
        model.addColumn("Id Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Merk");
        model.addColumn("Tipe");
        model.addColumn("Jumlah");
        model.addColumn("Harga");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPencarian = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        pilih = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kasir Conter HP");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/hp.png")).getImage());
        setSize(new java.awt.Dimension(641, 465));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hasil Pencarian");

        tbPencarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPencarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbPencarianMousePressed(evt);
            }
        });
        tbPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPencarianKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbPencarian);

        keterangan.setEditable(false);
        keterangan.setColumns(20);
        keterangan.setRows(5);
        keterangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                keteranganMousePressed(evt);
            }
        });
        keterangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keteranganKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(keterangan);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Keterangan");

        pilih.setText("Pilih Barang");
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = koneksi.konek();
        getData();
        if (isBarcode) {
            DefaultTableModel model = (DefaultTableModel) tbPencarian.getModel();
            int myindex = 0;
            pilihan = model.getValueAt(myindex, 0).toString() + " | " + model.getValueAt(myindex, 1).toString();
            halamanKasir.setIdentifier(pilihan);
            for (int i = 0; i < 6; i++) {
                halamanKasir.setSelect(i, model.getValueAt(myindex, i).toString());
            }
            halamanKasir.setSelect(6, ket.get(myindex));
            halamanKasir.refresh();
            halamanKasir.setJumlah(1);
            halamanKasir.setDataTable();
            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void tbPencarianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPencarianMousePressed
        DefaultTableModel model = (DefaultTableModel) tbPencarian.getModel();
        int myindex = tbPencarian.getSelectedRow();
        keterangan.setText(ket.get(myindex));
    }//GEN-LAST:event_tbPencarianMousePressed

    private void keteranganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keteranganKeyPressed

    }//GEN-LAST:event_keteranganKeyPressed

    private void keteranganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keteranganMousePressed

    }//GEN-LAST:event_keteranganMousePressed

    private void tbPencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPencarianKeyPressed
        DefaultTableModel model = (DefaultTableModel) tbPencarian.getModel();
        int myindex = tbPencarian.getSelectedRow();
        keterangan.setText(ket.get(myindex));
    }//GEN-LAST:event_tbPencarianKeyPressed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbPencarian.getModel();
        int myindex = tbPencarian.getSelectedRow();
        pilihan = model.getValueAt(myindex, 0).toString() + " | " + model.getValueAt(myindex, 1).toString();
        halamanKasir.setIdentifier(pilihan);
        for (int i = 0; i < 6; i++) {
            halamanKasir.setSelect(i, model.getValueAt(myindex, i).toString());
        }
        halamanKasir.setSelect(6, ket.get(myindex));
        halamanKasir.refresh();
        dispose();
    }//GEN-LAST:event_pilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JButton pilih;
    private javax.swing.JTable tbPencarian;
    // End of variables declaration//GEN-END:variables

    private void getData() {

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            ps = conn.prepareStatement("SELECT * FROM `tb_barang` WHERE (`id_barang` LIKE ? OR `nama_barang` LIKE ? OR `merk_barang` LIKE ? OR `tipe_barang` LIKE ? OR `keterangan` LIKE ? OR `barcode` LIKE ?) AND `jumlah` > 0");
            ps.setString(1, "%" + identifier + "%");
            ps.setString(2, "%" + identifier + "%");
            ps.setString(3, "%" + identifier + "%");
            ps.setString(4, "%" + identifier + "%");
            ps.setString(5, "%" + identifier + "%");
            ps.setString(6, "%" + identifier + "%");
            rs = ps.executeQuery();
            while (rs.next()) {
                Object[] obj = new Object[6];
                obj[0] = rs.getString("id_barang");
                obj[1] = rs.getString("nama_barang");
                obj[2] = rs.getString("merk_barang");
                obj[3] = rs.getString("tipe_barang");
                obj[4] = rs.getString("jumlah");
                obj[5] = rs.getString("harga");
                ket.add(rs.getRow() - 1, rs.getString("Keterangan"));
                model.addRow(obj);
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error SQL : " + e);
        }
    }
}
