/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package konterhp;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Baihaqi
 */
public class Input_barang extends javax.swing.JFrame {

    static public ResultSet dataLogin;
    ArrayList<String> ket = new ArrayList<>();
    private DefaultTableModel model;
    Connection conn;
    PreparedStatement ps;
    Statement cs;
    ResultSet rs ;

    /**
     * Creates new form newbarang
     */
    public Input_barang() {
        initComponents();
        model = new DefaultTableModel ();
        //digunakan untuk memberi heading / judul pada kolom di tabel buku
            tabel_produk.setModel(model);
// "table_buku sesuaikan dengan variabel name"
            model.addColumn("ID");
            model.addColumn("NAMA BARANG");
            model.addColumn("MERK");
            model.addColumn("TIPE");
            model.addColumn("JUMLAH");
            model.addColumn("HARGA");
    }
    
    private void getData(){
     
     model.getDataVector().removeAllElements();
     model.fireTableDataChanged();
 
     try{
           
//membuat statemen untuk memanggil data table tabel_buku
//           koneksi connection = new koneksi();   
//           Statement stat = connection.getKoneksi().createStatement( );
//           String sql        = "Select * from tabel_buku";
                cs = conn.createStatement();
                rs = cs.executeQuery("Select * from tb_barang");
                
//pengecekan terhadap data tabel_buku
           while(rs.next ()){
                Object[] obj = new Object[6];
                obj[0] = rs.getString("id_barang");
                obj[1] = rs.getString("nama_barang");
                obj[2] = rs.getString("merk_barang");
                obj[3] = rs.getString("tipe_barang");
                obj[4] = rs.getString("jumlah");
                obj[5] = rs.getString("harga");
                ket.add(rs.getRow()-1, rs.getString("Keterangan"));
                model.addRow(obj);
            }
            rs.close();
            cs.clearBatch();
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        merk = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        keterangan = new java.awt.TextArea();
        btn_update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tambah_pr = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_produk = new javax.swing.JTable();
        tb_stok = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        nama_br = new javax.swing.JTextField();
        tgl = new com.toedter.calendar.JDateChooser();
        id_barang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 4, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 4, 0));
        jLabel1.setText("MANAGE PRODUCT");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nama Barang");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Merk");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Type");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Keterangan edit");

        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkActionPerformed(evt);
            }
        });

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(240, 4, 0));
        btn_update.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("EDIT");
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(240, 4, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tambah Stok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tambah_pr.setBackground(new java.awt.Color(240, 4, 0));
        tambah_pr.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tambah_pr.setForeground(new java.awt.Color(255, 255, 255));
        tambah_pr.setText("Tambah Produk");
        tambah_pr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_prMouseClicked(evt);
            }
        });
        tambah_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_prActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(240, 4, 0));
        clear.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 4, 0));
        jLabel2.setText("LIST PRODUK");

        tabel_produk.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabel_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "wkwk", "rere", null, "1200000", "12"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA BARANG", "MERK", "TIPE", "HARGA", "JUMLAH"
            }
        ));
        tabel_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_produkMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabel_produkMousePressed(evt);
            }
        });
        tabel_produk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabel_produkKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_produk);

        tb_stok.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tb_stokStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Tanggal");

        nama_br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_brActionPerformed(evt);
            }
        });

        id_barang.setEditable(false);
        id_barang.setBackground(new java.awt.Color(255, 255, 255));
        id_barang.setForeground(new java.awt.Color(255, 255, 255));
        id_barang.setActionCommand("<Not Set>");
        id_barang.setCaretColor(new java.awt.Color(255, 255, 255));
        id_barang.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        id_barang.setEnabled(false);
        id_barang.setSelectionColor(new java.awt.Color(255, 255, 255));
        id_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tambah_pr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_update)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clear)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(merk, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama_br, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(25, 25, 25)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tb_stok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel10)
                                .addComponent(nama_br, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(keterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah_pr)
                    .addComponent(jButton2)
                    .addComponent(btn_update)
                    .addComponent(clear)
                    .addComponent(tb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        nama_br.setText("");
        merk.setText("");
        type.setText("");
        harga.setText("");
        jumlah.setText("");
        keterangan.setText("");
        tambah_pr.setEnabled(true);
       
    }//GEN-LAST:event_clearMouseClicked

    private void tambah_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_prActionPerformed

    }//GEN-LAST:event_tambah_prActionPerformed

    private void tambah_prMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_prMouseClicked
        Calendar Time = tgl.getCalendar();
        if (nama_br.getText().isEmpty() || merk.getText().isEmpty() || type.getText().isEmpty() || harga.getText().isEmpty() || jumlah.getText().isEmpty()|| keterangan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukan informasi produk");
        }
        else{
            try {
                ps = conn.prepareStatement("insert into tb_barang values (NULL,?,?,?,?,?,?)");
                ps.setString(1, nama_br.getText());
                ps.setString(2, merk.getText());
                ps.setString(3, type.getText());
                ps.setInt(4, Integer.parseInt(harga.getText()));
                ps.setInt(5, Integer.parseInt(jumlah.getText()));
                ps.setString(6, keterangan.getText());
                ps.executeUpdate();
                
                cs = conn.createStatement();
                rs = ps.executeQuery("SELECT * FROM tb_barang ORDER BY `id_barang` DESC LIMIT 1");
                rs.next();
                
                int x = rs.getInt("id_barang");
                rs.close();
                ps.clearBatch();
                
                ps = conn.prepareStatement("INSERT INTO `tb_barang_masuk` (`id`, `id_barang`, `jumlah_masuk`, `tanggal_masuk`, `ketersediaan`) VALUES (NULL, ?, ?, ?, ?);");
                ps.setInt(1, x);
                ps.setInt(2, Integer.parseInt(jumlah.getText()));
                ps.setString(3, Time.get(Calendar.YEAR)+"-"+(Time.get(Calendar.MONTH)+1)+"-"+Time.get(Calendar.DATE));
                ps.setInt(4, Integer.parseInt(jumlah.getText()));
                if(ps.executeUpdate() == 1){
                    getData();
                    JOptionPane.showMessageDialog(this, "Produk berhasil di tambah");
                     nama_br.setText("");
                    merk.setText("");
                    type.setText("");
                    harga.setText("");
                    jumlah.setText("");
                    keterangan.setText("");
                rs.close();
                ps.clearBatch();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Input_barang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tambah_prMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merkActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         conn = koneksi.konek();
         tgl.setDate(new Date(System.currentTimeMillis()));
         getData();
    }//GEN-LAST:event_formWindowOpened

    private void nama_brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_brActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_brActionPerformed

    private void id_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_barangActionPerformed

    private void tabel_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_produkMouseClicked

    }//GEN-LAST:event_tabel_produkMouseClicked

    private void tb_stokStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tb_stokStateChanged
       if(Integer.parseInt(tb_stok.getValue().toString()) < 0){
           tb_stok.setValue(0);
       }
    }//GEN-LAST:event_tb_stokStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Calendar Time = tgl.getCalendar();
        try {
            // TODO add your handling code here: int id = Integer.parseInt(id_barang.getText());
              String id = id_barang.getText();
             ps = conn.prepareStatement("SELECT `id_barang`,`jumlah` FROM `tb_barang` WHERE `id_barang`= ?");
               ps.setString(1, id);
               rs = ps.executeQuery();
                rs.next();
                
                int stoklama = rs.getInt("jumlah");
                int stokbr = Integer.parseInt(tb_stok.getValue().toString());
                int update = stokbr + stoklama;

            ps = conn.prepareStatement("UPDATE `tb_barang` SET `jumlah`= ? WHERE `id_barang`= ?");
             ps.setInt(1, update);
             ps.setString(2, id);
             ps.executeUpdate();
             
               ps = conn.prepareStatement("UPDATE `tb_barang_masuk` SET `jumlah_masuk`= ?,`tanggal_masuk`= ?,`ketersediaan`= ? WHERE `id_barang`= ?");
             ps.setString(1,  tb_stok.getValue().toString());
             ps.setString(2, Time.get(Calendar.YEAR)+"-"+(Time.get(Calendar.MONTH)+1)+"-"+Time.get(Calendar.DATE));
             ps.setInt(3, update);
             ps.setString(4, id);
              ps.executeUpdate();
            
             getData();
             JOptionPane.showMessageDialog(this, "Berhasil di tambah");
            
        } catch (SQLException ex) {
            Logger.getLogger(Input_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jButton2MouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // TODO add your handling code here:
        try {
             ps = conn.prepareStatement("UPDATE `tb_barang` SET `id_barang`= ?,`nama_barang`= ?,`merk_barang`= ?,`tipe_barang`= ?,`harga`= ?,`jumlah`= ?,`keterangan`= ? WHERE `id_barang`= ?");
            ps.setString(1, id_barang.getText());
            ps.setString(2, nama_br.getText());
            ps.setString(3, merk.getText());
            ps.setString(4, type.getText());
            ps.setInt(5, Integer.parseInt(harga.getText()));
            ps.setInt(6, Integer.parseInt(jumlah.getText()));
            ps.setString(7, keterangan.getText());
            ps.setString(8, id_barang.getText());
            ps.executeUpdate();
            
             JOptionPane.showMessageDialog(this, "Data berhasil di update");
            
        } catch (SQLException ex) {
            Logger.getLogger(Input_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateMouseClicked

    private void tabel_produkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_produkMousePressed
        DefaultTableModel model = (DefaultTableModel)tabel_produk.getModel();
        int myindex = tabel_produk.getSelectedRow();
        id_barang.setText(model.getValueAt(myindex, 0).toString());
        nama_br.setText(model.getValueAt(myindex, 1).toString());
        merk.setText(model.getValueAt(myindex, 2).toString());
        type.setText(model.getValueAt(myindex, 3).toString());
        jumlah.setText(model.getValueAt(myindex, 4).toString());
        harga.setText(model.getValueAt(myindex, 5).toString());
        keterangan.setText(ket.get(myindex)); 
                        
        tambah_pr.setEnabled(false);
    }//GEN-LAST:event_tabel_produkMousePressed

    private void tabel_produkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_produkKeyPressed
        DefaultTableModel model = (DefaultTableModel)tabel_produk.getModel();
        int myindex = tabel_produk.getSelectedRow();
        id_barang.setText(model.getValueAt(myindex, 0).toString());
        nama_br.setText(model.getValueAt(myindex, 1).toString());
        merk.setText(model.getValueAt(myindex, 2).toString());
        type.setText(model.getValueAt(myindex, 3).toString());
        jumlah.setText(model.getValueAt(myindex, 4).toString());
        harga.setText(model.getValueAt(myindex, 5).toString());
        keterangan.setText(ket.get(myindex)); 
                        
        tambah_pr.setEnabled(false);
    }//GEN-LAST:event_tabel_produkKeyPressed
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_barang().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JButton clear;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_barang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private java.awt.TextArea keterangan;
    private javax.swing.JTextField merk;
    private javax.swing.JTextField nama_br;
    private javax.swing.JTable tabel_produk;
    private javax.swing.JButton tambah_pr;
    private javax.swing.JSpinner tb_stok;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
