/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konterhp;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import static konterhp.Home_Laporan.dataLogin;
import static konterhp.laporan_brg_masuk.dataLogin;

/**
 *
 * @author ASUS
 */
public class Karyawan extends javax.swing.JFrame {

    static ResultSet dataLogin;
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    Statement cs;
    private DefaultTableModel model;
    ArrayList<String> timestamp_tgl_lahir = new ArrayList<>();
    ArrayList<String> jabatan = new ArrayList<>();
    ArrayList<String> image = new ArrayList<>();
    String filename;
    private String foto;

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        model = new DefaultTableModel();
        //digunakan untuk memberi heading / judul pada kolom di tabel buku
        tb_data.setModel(model);
// "table_buku sesuaikan dengan variabel name"
        model.addColumn("NAMA");
        model.addColumn("ID PEGAWAI");
        model.addColumn("NIK");
        model.addColumn("TEMPAT LAHIR");
        model.addColumn("TANGGAL LAHIR");
        model.addColumn("KEWARNEGARAAN");
        model.addColumn("ALAMAT");
        model.addColumn("JABATAN");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("AGAMA");
        model.addColumn("GAJI");
        model.addColumn("STATUS");
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public void refreshFoto() {
        File f = new File(this.foto);
        ImageIcon icon = new ImageIcon(f.toString());
        Image img = icon.getImage().getScaledInstance(label_foto.getWidth(), label_foto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        label_foto.setIcon(ic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tgl_lahir = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_tempatlahir = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cb_jabatan = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        rd_laki = new javax.swing.JRadioButton();
        rd_perempuan = new javax.swing.JRadioButton();
        btn_clear = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_kewarnegaraan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_agama = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_gaji = new javax.swing.JTextField();
        btn_tambahjabatan = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        label_foto = new javax.swing.JLabel();
        btn_pilihfoto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 249, 253));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/hp.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(33, 85, 205));

        jLabel1.setBackground(new java.awt.Color(10, 161, 221));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 240, 250));
        jLabel1.setText("DATA KARYAWAN");

        jPanel1.setBackground(new java.awt.Color(232, 249, 253));
        jPanel1.setForeground(new java.awt.Color(232, 249, 253));
        jPanel1.setToolTipText("");

        jLabel4.setText("NAMA");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel16.setText("TANGGAL LAHIR");

        tgl_lahir.setDateFormatString("d-MM-y");
        tgl_lahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_lahirPropertyChange(evt);
            }
        });

        jLabel14.setText("ALAMAT");

        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });

        jLabel15.setText("KEWARGANEGARAAN");

        txt_alamat.setMaximumSize(new java.awt.Dimension(64, 22));
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        jLabel18.setText("JABATAN");

        cb_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jabatanActionPerformed(evt);
            }
        });

        jLabel17.setText("JENIS KELAMIN");

        buttonGroup1.add(rd_laki);
        rd_laki.setText("LAKI-LAKI");
        rd_laki.setActionCommand("LAKI-LAKI");
        rd_laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_lakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_perempuan);
        rd_perempuan.setText("PEREMPUAN");
        rd_perempuan.setActionCommand("PEREMPUAN");
        rd_perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_perempuanActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(33, 85, 205));
        btn_clear.setForeground(new java.awt.Color(221, 240, 250));
        btn_clear.setText("CLEAR");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(33, 85, 205));
        btn_edit.setForeground(new java.awt.Color(221, 240, 250));
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_tambah.setBackground(new java.awt.Color(33, 85, 205));
        btn_tambah.setForeground(new java.awt.Color(221, 240, 250));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "ID PEGAWAI", "NIK", "TEMPAT LAHIR", "TANGGAL LAHIR", "KEWARNEGARAAN", "ALAMAT", "JABATAN", "JENIS KELAMIN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_dataMousePressed(evt);
            }
        });
        tb_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_dataKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_dataKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_data);

        jLabel10.setText("NIK");

        jLabel13.setText("TEMPAT LAHIR");

        cb_kewarnegaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WNI", "WNA" }));
        cb_kewarnegaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kewarnegaraanActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(232, 249, 253));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 85, 205));
        jLabel2.setText("TABEL KARYAWAN");

        jLabel19.setText("AGAMA");

        cb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM ", "KRISTEN ", "HINDU", "BUDHA", "KONGHUCHU" }));

        jLabel5.setText("GAJI");

        txt_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gajiActionPerformed(evt);
            }
        });

        btn_tambahjabatan.setBackground(new java.awt.Color(33, 85, 205));
        btn_tambahjabatan.setForeground(new java.awt.Color(221, 240, 250));
        btn_tambahjabatan.setText("+");
        btn_tambahjabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahjabatanMouseClicked(evt);
            }
        });
        btn_tambahjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahjabatanActionPerformed(evt);
            }
        });

        jLabel20.setText("STATUS");

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AKTIF", "NONAKTIF" }));
        cb_status.setMinimumSize(new java.awt.Dimension(108, 22));
        cb_status.setPreferredSize(new java.awt.Dimension(108, 22));
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });

        label_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_pilihfoto.setBackground(new java.awt.Color(33, 85, 205));
        btn_pilihfoto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btn_pilihfoto.setForeground(new java.awt.Color(221, 240, 250));
        btn_pilihfoto.setText("PILIH FOTO");
        btn_pilihfoto.setBorder(null);
        btn_pilihfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihfotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(btn_clear)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btn_tambah)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_tempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tambahjabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                                    .addComponent(cb_agama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_pilihfoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_kewarnegaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_gaji)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rd_laki)
                                .addGap(18, 18, 18)
                                .addComponent(rd_perempuan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(283, 283, 283))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_tempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cb_kewarnegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(rd_laki)
                            .addComponent(rd_perempuan)
                            .addComponent(btn_tambahjabatan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel5)
                            .addComponent(txt_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel20)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_pilihfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_clear)
                                    .addComponent(btn_edit)
                                    .addComponent(btn_tambah))
                                .addGap(197, 197, 197))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(label_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jButton4.setBackground(new java.awt.Color(33, 85, 205));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(221, 240, 250));
        jButton4.setText("< BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cb_status.setSelectedIndex(0);
        cb_status.setEnabled(false);
        conn = koneksi.konek();
        try {
            cs = conn.createStatement();
            rs = cs.executeQuery("select * from tb_config");
            while (rs.next()) {
                jabatan.add(rs.getString("jabatan").toUpperCase());
                cb_jabatan.addItem(rs.getString("jabatan").toUpperCase());
            }
            getData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Home_Admin pindah = new Home_Admin();
        Home_Admin.dataLogin = dataLogin;
        pindah.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb_kewarnegaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kewarnegaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_kewarnegaraanActionPerformed

    private void tb_dataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_dataKeyReleased
        DefaultTableModel model = (DefaultTableModel) tb_data.getModel();
        int myindex = tb_data.getSelectedRow();
        txt_nama.setText(model.getValueAt(myindex, 0).toString());
        txt_nik.setText(model.getValueAt(myindex, 2).toString());
        txt_tempatlahir.setText(model.getValueAt(myindex, 3).toString());
        tgl_lahir.setDate(new Date(Long.parseLong(String.valueOf(timestamp_tgl_lahir.get(myindex) + "000"))));
        txt_alamat.setText(model.getValueAt(myindex, 6).toString());

        switch (model.getValueAt(myindex, 5).toString()) {
            case "WNI":
                cb_kewarnegaraan.setSelectedIndex(0);
                break;
            case "WNA":
                cb_kewarnegaraan.setSelectedIndex(1);
                break;
        }
        for (int i = 0; i < jabatan.size(); i++) {
            if (model.getValueAt(myindex, 7).toString().equals(jabatan.get(i))) {
                cb_jabatan.setSelectedIndex(i);
                break;
            }
        }
        switch (model.getValueAt(myindex, 8).toString()) {
            case "LAKI-LAKI":
                buttonGroup1.setSelected(rd_laki.getModel(), rootPaneCheckingEnabled);
                break;
            case "PEREMPUAN":
                buttonGroup1.setSelected(rd_perempuan.getModel(), rootPaneCheckingEnabled);
                break;
        }
        switch (model.getValueAt(myindex, 8).toString()) {
            case "LAKI-LAKI":
                buttonGroup1.setSelected(rd_laki.getModel(), rootPaneCheckingEnabled);
                break;
            case "PEREMPUAN":
                buttonGroup1.setSelected(rd_perempuan.getModel(), rootPaneCheckingEnabled);
                break;
        }
        switch (model.getValueAt(myindex, 9).toString()) {
            case "ISLAM":
                cb_agama.setSelectedIndex(0);
                break;
            case "KRISTEN":
                cb_agama.setSelectedIndex(1);
                break;
            case "HINDU":
                cb_agama.setSelectedIndex(2);
                break;
            case "BUDHA":
                cb_agama.setSelectedIndex(3);
                break;
            case "KONGHUCHU":
                cb_agama.setSelectedIndex(4);
                break;
        }
        txt_gaji.setText(model.getValueAt(myindex, 10).toString());
        cb_status.setEnabled(true);
        btn_tambah.setEnabled(false);

        switch (model.getValueAt(myindex, 11).toString()) {
            case "AKTIF":
                cb_kewarnegaraan.setSelectedIndex(0);
                break;
            case "NONAKTIF":
                cb_kewarnegaraan.setSelectedIndex(1);
                break;
        }

        setFoto(image.get(myindex));
        refreshFoto();
    }//GEN-LAST:event_tb_dataKeyReleased

    private void tb_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_dataKeyPressed

    }//GEN-LAST:event_tb_dataKeyPressed

    private void tb_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMousePressed
        DefaultTableModel model = (DefaultTableModel) tb_data.getModel();
        int myindex = tb_data.getSelectedRow();
        txt_nama.setText(model.getValueAt(myindex, 0).toString());
        txt_nik.setText(model.getValueAt(myindex, 2).toString());
        txt_tempatlahir.setText(model.getValueAt(myindex, 3).toString());
        tgl_lahir.setDate(new Date(Long.parseLong(String.valueOf(timestamp_tgl_lahir.get(myindex) + "000"))));
        txt_alamat.setText(model.getValueAt(myindex, 6).toString());
        switch (model.getValueAt(myindex, 5).toString()) {
            case "WNI":
                cb_kewarnegaraan.setSelectedIndex(0);
                break;
            case "WNA":
                cb_kewarnegaraan.setSelectedIndex(1);
                break;
        }
        for (int i = 0; i < jabatan.size(); i++) {
            if (model.getValueAt(myindex, 7).toString().equals(jabatan.get(i))) {
                cb_jabatan.setSelectedIndex(i);
                break;
            }
        }
        switch (model.getValueAt(myindex, 8).toString()) {
            case "LAKI-LAKI":
                buttonGroup1.setSelected(rd_laki.getModel(), rootPaneCheckingEnabled);
                break;
            case "PEREMPUAN":
                buttonGroup1.setSelected(rd_perempuan.getModel(), rootPaneCheckingEnabled);
                break;
        }

        switch (model.getValueAt(myindex, 9).toString()) {
            case "ISLAM":
                cb_agama.setSelectedIndex(0);
                break;
            case "KRISTEN":
                cb_agama.setSelectedIndex(1);
                break;
            case "HINDU":
                cb_agama.setSelectedIndex(2);
                break;
            case "BUDHA":
                cb_agama.setSelectedIndex(3);
                break;
            case "KONGHUCHU":
                cb_agama.setSelectedIndex(4);
                break;
        }
        txt_gaji.setText(model.getValueAt(myindex, 10).toString());
        cb_status.setEnabled(true);
        btn_tambah.setEnabled(false);

        switch (model.getValueAt(myindex, 11).toString()) {
            case "AKTIF":
                cb_kewarnegaraan.setSelectedIndex(0);
                break;
            case "NONAKTIF":
                cb_kewarnegaraan.setSelectedIndex(1);
                break;
        }
        setFoto(image.get(myindex));
        refreshFoto();
    }//GEN-LAST:event_tb_dataMousePressed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        Calendar Time = tgl_lahir.getCalendar();
        if (txt_nama.getText().isEmpty() || txt_nik.getText().isEmpty() || txt_tempatlahir.getText().isEmpty() || txt_alamat.getText().isEmpty() || cb_kewarnegaraan.getSelectedItem().toString().isEmpty() || Time == null) {
            JOptionPane.showMessageDialog(this, "masukkan data pegawai");
        } else {
            daftar_akun halamanAkun = new daftar_akun(this, Time);
            halamanAkun.setVisible(true);
            //tambahAkun(Time);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearData();
        cb_status.setSelectedIndex(0);
        cb_status.setEnabled(false);
        btn_tambah.setEnabled(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearMouseClicked

    private void rd_perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_perempuanActionPerformed

    private void rd_lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_lakiActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void tgl_lahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_lahirPropertyChange
        //System.out.println(new SimpleDateFormat(""));
    }//GEN-LAST:event_tgl_lahirPropertyChange

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gajiActionPerformed

    private void cb_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_jabatanActionPerformed

    private void btn_tambahjabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahjabatanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahjabatanMouseClicked

    private void btn_tambahjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahjabatanActionPerformed
        // TODO add your handling code here:
        String tambahJabatan;
        try {
            tambahJabatan = JOptionPane.showInputDialog("masukkan jabatan baru");
            ps = conn.prepareStatement("insert into tb_config values (NULL,?)");
            ps.setString(1, tambahJabatan);
            ps.executeUpdate();
            jabatan.clear();
            cb_jabatan.removeAllItems();
            cs = conn.createStatement();
            rs = cs.executeQuery("select * from tb_config");
            while (rs.next()) {
                jabatan.add(rs.getString("jabatan").toUpperCase());
                cb_jabatan.addItem(rs.getString("jabatan").toUpperCase());
            }
            JOptionPane.showMessageDialog(null, "JABATAN BERHASIL DITAMBAHKAN", "BERHASIL", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "TERDAPAT KESALAHAN DATA", "KESALAHAN", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_tambahjabatanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Edit Username dan Password?", "EDIT", JOptionPane.YES_NO_OPTION) == 0) {
            daftar_akun da = new daftar_akun(this, tgl_lahir.getCalendar());
            da.isEdit();
            da.setVisible(true);
        } else {
            editdata(tgl_lahir.getCalendar());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_statusActionPerformed

    private void btn_pilihfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihfotoActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(label_foto.getWidth(), label_foto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic = new ImageIcon(img);
            label_foto.setIcon(ic);
            this.filename = f.getAbsolutePath();
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btn_pilihfotoActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_pilihfoto;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambahjabatan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_agama;
    private javax.swing.JComboBox<String> cb_jabatan;
    private javax.swing.JComboBox<String> cb_kewarnegaraan;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_foto;
    private javax.swing.JRadioButton rd_laki;
    private javax.swing.JRadioButton rd_perempuan;
    private javax.swing.JTable tb_data;
    private com.toedter.calendar.JDateChooser tgl_lahir;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_gaji;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_tempatlahir;
    // End of variables declaration//GEN-END:variables

    private void clearData() {
        txt_nama.setText("");
        txt_nik.setText("");
        txt_tempatlahir.setText("");
        txt_alamat.setText("");
        cb_kewarnegaraan.setSelectedIndex(0);
        btn_tambah.setEnabled(true);
        tgl_lahir.setCalendar(null);
        txt_gaji.setText("");
        cb_agama.setSelectedIndex(0);
        cb_status.setSelectedIndex(0);
        label_foto.setIcon(null);
    }

    private void getData() {

        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            cs = conn.createStatement();
            rs = cs.executeQuery("SELECT tb_pegawai.id_pegawai, tb_pegawai.nik, tb_pegawai.nama, tb_pegawai.tempat_lahir, tb_pegawai.alamat, tb_pegawai.kewarganegaraan, tb_pegawai.jenis_kelamin, tb_pegawai.agama, tb_pegawai.gaji, tb_pegawai.status_pegawai, tb_pegawai.foto ,tb_user.level, UNIX_TIMESTAMP(`tb_pegawai`.`tanggal_lahir`) as tanggal_lahir_timestamp, tb_pegawai.`tanggal_lahir` FROM `tb_pegawai`, `tb_user` WHERE tb_pegawai.id_pegawai = tb_user.id_pegawai");
            image.clear();
            while (rs.next()) {
                Object[] obj = new Object[13];
                obj[0] = rs.getString("nama");
                obj[1] = rs.getString("id_pegawai");
                obj[2] = rs.getString("nik");
                obj[3] = rs.getString("tempat_lahir");
                obj[4] = rs.getString("tanggal_lahir");
                obj[5] = rs.getString("kewarganegaraan");
                obj[6] = rs.getString("alamat");
                obj[7] = rs.getString("level");
                obj[8] = rs.getString("jenis_kelamin");
                obj[9] = rs.getString("agama");
                obj[10] = rs.getString("gaji");
                obj[11] = rs.getString("status_pegawai");
                image.add(rs.getString("foto"));
                timestamp_tgl_lahir.add(rs.getRow() - 1, rs.getString("tanggal_lahir_timestamp"));
                model.addRow(obj);
            }
            rs.close();
            cs.clearBatch();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    public void tambahAkun(Calendar Time, String user, String password) throws IOException {
        int x = 0;
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        File fileawal = null;
        File fileakhir = null;
        try {
            if (filename != null) {
                String newpath = "src/upload";
                File directory = new File(newpath);
                if (!directory.exists()) {
                    directory.mkdirs();
                }
                System.out.print(filename);
                String ext = filename.substring(filename.lastIndexOf('.') + 1);
                fileawal = new File(filename);
                fileakhir = new File(newpath + "/" + txt_nama.getText() + "_" + String.valueOf(timestamp.getTime()) + "." + ext);
                Files.copy(fileawal.toPath(), fileakhir.toPath());
            }
            ps = conn.prepareStatement("insert into tb_pegawai values (NULL,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txt_nik.getText());
            ps.setString(2, txt_nama.getText());
            ps.setString(3, txt_tempatlahir.getText());
            ps.setString(4, Time.get(Calendar.YEAR) + "-" + (Time.get(Calendar.MONTH) + 1) + "-" + Time.get(Calendar.DATE));
            ps.setString(5, txt_alamat.getText());
            ps.setString(6, cb_kewarnegaraan.getSelectedItem().toString());
            ps.setString(7, buttonGroup1.getSelection().getActionCommand());
            ps.setString(8, cb_agama.getSelectedItem().toString());
            ps.setString(9, txt_gaji.getText());
            ps.setString(10, cb_status.getSelectedItem().toString());
            ps.setString(11, fileakhir != null ? fileakhir.toString() : "");
            ps.executeUpdate();
            rs = ps.executeQuery("SELECT * FROM tb_pegawai ORDER BY `id_pegawai` DESC LIMIT 1");
            rs.next();
            x = rs.getInt("id_pegawai");
            rs.close();
            ps.clearBatch();
            System.out.println(cb_jabatan.getSelectedItem().toString());
            ps = conn.prepareStatement("insert into tb_user values (NULL,?,MD5(?),?,?)");
            ps.setString(1, user);
            ps.setString(2, password);
            ps.setString(3, cb_jabatan.getSelectedItem().toString());
            ps.setString(4, String.valueOf(x));
            ps.executeUpdate();
            rs.close();
            ps.clearBatch();
            clearData();
            JOptionPane.showMessageDialog(this, "DATA BRHASIL DITAMBAHKAN");
        } catch (SQLException e) {
            try {
                ps = conn.prepareStatement("DELETE FROM tb_pegawai WHERE `id_pegawai` = ?");
                ps.setString(1, String.valueOf(x));
                ps.executeUpdate();
            } catch (SQLException ev) {
            }
            JOptionPane.showMessageDialog(this, "TERDAPAT KESALAHAN DATA");
        } finally {
            getData();
        }

    }

    void editdata(Calendar Time) {
        // TODO add your handling code here:
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        File fileawal = null;
        File fileakhir = null;
        try {
            if (filename != null) {
                String newpath = "src/upload";
                File directory = new File(newpath);
                if (!directory.exists()) {
                    directory.mkdirs();
                }
                System.out.print(filename);
                String ext = filename.substring(filename.lastIndexOf('.') + 1);
                fileawal = new File(filename);
                fileakhir = new File(newpath + "/" + txt_nama.getText() + "_" + String.valueOf(timestamp.getTime()) + "." + ext);
                Files.copy(fileawal.toPath(), fileakhir.toPath());
            }
            ps = conn.prepareStatement("UPDATE tb_pegawai SET `nik`=?,`nama`=?,`tempat_lahir`=?,`tanggal_lahir`=?,`alamat`=?,`kewarganegaraan`=?,`jenis_kelamin`=?,`agama`=?,`gaji`=?,`status_pegawai`=?,`foto`=? WHERE `id_pegawai`=?");
            ps.setString(1, txt_nik.getText());
            ps.setString(2, txt_nama.getText());
            ps.setString(3, txt_tempatlahir.getText());
            ps.setString(4, Time.get(Calendar.YEAR) + "-" + (Time.get(Calendar.MONTH) + 1) + "-" + Time.get(Calendar.DATE));
            ps.setString(5, txt_alamat.getText());
            ps.setString(6, cb_kewarnegaraan.getSelectedItem().toString());
            ps.setString(7, buttonGroup1.getSelection().getActionCommand());
            ps.setString(8, cb_agama.getSelectedItem().toString());
            ps.setInt(9, Integer.parseInt(txt_gaji.getText()));
            ps.setString(10, cb_status.getSelectedItem().toString().toLowerCase());
            ps.setString(11, fileakhir != null ? fileakhir.toString() : "");
            ps.setInt(12, Integer.parseInt(tb_data.getValueAt(tb_data.getSelectedRow(), 1).toString()));
            ps.executeUpdate();
            ps.clearBatch();

            ps = conn.prepareStatement("UPDATE `tb_user` SET `level` = ? WHERE `tb_user`.`id_pegawai` = ?");
            ps.setString(1, cb_jabatan.getSelectedItem().toString());
            ps.setInt(2, Integer.parseInt(tb_data.getValueAt(tb_data.getSelectedRow(), 1).toString()));
            ps.executeUpdate();
            clearData();
            getData();
            JOptionPane.showMessageDialog(this, "DATA BERHASIL DIEDIT");
        } catch (IOException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "TERDAPAT KESALAHAN DATA -> " + e);
        }
    }

    void editDataUser(String usernameEdit, String passwordEdit) {
        try {
            ps = conn.prepareStatement("UPDATE `tb_user` SET `user` = ?, `password` = MD5(?) WHERE `tb_user`.`id_pegawai` = ?");
            ps.setString(1, usernameEdit);
            ps.setString(2, passwordEdit);
            ps.setInt(3, Integer.parseInt(tb_data.getValueAt(tb_data.getSelectedRow(), 1).toString()));
            ps.executeUpdate();
        } catch (NumberFormatException | SQLException e) {
        }
    }

}
